<a href="https://colab.research.google.com/github/ErAniketKumar/PythonBasic/blob/main/numpy_arraybasic1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#in list we can only store 1d array so we use numpy array

a=np.array([1,2,3,4,5])
print(a)
#2d array
b=np.array([[1,2,3],
            [3,4,5],
            [2,0,9]])
print(b)

[1 2 3 4 5]
[[1 2 3]
 [3 4 5]
 [2 0 9]]


In [ ]:
print(a.size) #number of element in array
print(b.size)

print(a.shape)
print(b.shape) #(row, columns)

#data type

print(a.dtype)
print(b.dtype)

#transpose

print(b.transpose()) #transpose the data of matrix row goes to column and column goes to row


5
9
(5,)
(3, 3)
int64
int64
[[1 3 2]
 [2 4 0]
 [3 5 9]]


In [ ]:
print(np.empty((3,3), dtype = int)) #print 3x3 matrix and data in randomly generate and data type of data is int


[[94104784797233              0              0]
 [             0              0              0]
 [             0              0              0]]


In [ ]:
x=np.ones(6)
print(x)

[1. 1. 1. 1. 1. 1.]


In [ ]:

y=np.ones((3,5)) # 3 row and 5 columns all data is one and float type
y



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
z=np.ones((3,3), dtype=int) # 3x3 matrix all data is 1 and data type of element is int
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
c=np.zeros((4,4));
c

d=np.zeros((4,4), dtype=int)
d

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
from os import fchdir
#string

e=np.zeros((4,4), dtype=str)
e
# zero i.e null;


f=np.ones((4,4), dtype=str)
f

#boolian

g=np.ones((3,3), dtype=bool)
g

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])