<a href="https://colab.research.google.com/github/ErAniketKumar/NumPy/blob/main/numpyBasic1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# print("jai mata di")

jai mata di


In [ ]:
#numoy:- numerical python
#in 2005, travus oliphant created NumPy package.
# it is a package that defines a multidimention object
#and associate fast math function

# also has function for wordling domain linear like forier transformation trigo inverse and math,atical fundamental




In [ ]:
#array contiguous memory location it contain homogeneous data type
import numpy as np;


In [ ]:
l1=[10,20,30]
l2=[40,50,60];
print(l1+l2); #concinate both value and output show [10,20,30,40,50,60] no mathemitical operation
# but
a=np.array([10,20,30])
b=np.array([40,50,60])
print(a+b) # here perform mqathimatical operation
type(l1)# i.e l1 and l2 is not a array it is a list in python
type(a)#but a and b is numpy array through numpy thorough library
print(a*b) #also do mathmatical operation



[10, 20, 30, 40, 50, 60]
[50 70 90]
[ 400 1000 1800]


In [ ]:
arr=np.array([10,20,30,40,50,100])
brr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(brr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#slicing in numpy

print(arr[0:5]) # I.E 0 INDEX TO 5 ELEMENT

print(arr[3:])# start with 3rd index frint till the end
print(arr[2]) #print only index
print(arr[1:4]) #starting index to ending index

print(brr[2,1:]) # STARTING ROW STATRING INDEX IN 2D MATRIX
print(np.shape(brr)) #show row and column
print(np.ndim(brr)) #show aray dimention i.e 2d , 1d, 3d array

print(arr.dtype) #type show which type of element are store






[10 20 30 40 50]
[ 40  50 100]
30
[20 30 40]
[8 9]
(3, 3)
2
int64


In [ ]:
#inspecting of array
#a.shape -- array dimention row column
# len(a) length of array
# b.ndim-- number of array dimention
# e.size -- number of array element
# b.dtype - data type of array element
# b.astype(int) convert on array to a diferent type


In [ ]:
import numpy as np
a=[[30,40,50],[20,50,60]];
arr=np.array(a);
print(arr);
print(arr.shape)
print(len(arr)) #length of inner array
print(np.size(arr)) #no of total element
print(type(arr))
print(arr.dtype)
print(arr.astype(float)) #value print in the form of float
#also we can declear float array and conver value in int


[[30 40 50]
 [20 50 60]]
(2, 3)
2
6
<class 'numpy.ndarray'>
int64
[[30. 40. 50.]
 [20. 50. 60.]]


In [ ]:
#mathematical operations and function
import numpy as np
arr1=np.array([10,20,30,40]);
arr2=np.array([30,40,50,60]);
print(arr1+arr2) #both are same
print(np.add(arr1, arr2)) #same as above line

a1=[[10,20],[30,40]];
a2=[[40,50],[60,70]];
print(a1+a2) # value not add but both array merge
print(np.add(a1,a2))
print(arr1-arr2);
print(np.power(arr1,arr2))


[ 40  60  80 100]
[ 40  60  80 100]
[[10, 20], [30, 40], [40, 50], [60, 70]]
[[ 50  70]
 [ 90 110]]
[-20 -20 -20 -20]
[5076944270305263616                   0 1694479359798149120
                   0]


In [ ]:
#conbinning and splitting array
